//! The contract of Mold: for the same data, the runtime interpreter and the code generated by `#[derive(Mold)]`
//! produce the same bytes. Every case of the shared corpus (`smeltery-mold/tests/corpus/<case>/`) is rendered both
//! ways and compared with its `expected.html`.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use smeltery_mold::{Host, Template, Value};
use smeltery_mold_macros::Mold;
use std::collections::BTreeMap;

struct TestHost {
    title_errors: Vec<String>,
}

impl Host for TestHost {
    fn csrf_token(&self) -> Option<&str> {
        Some("tok<&>")
    }
    fn authenticated(&self) -> bool {
        true
    }
    fn errors(&self, field: &str) -> &[String] {
        if field == "title" {
            &self.title_errors
        } else {
            &[]
        }
    }
    fn old(&self, field: &str) -> Option<&str> {
        (field == "title").then_some("Old <title>")
    }
    fn session(&self, key: &str) -> Option<String> {
        (key == "status").then(|| "Saved <ok>".to_owned())
    }
    fn route(&self, name: &str, params: &[(String, String)]) -> Result<String, String> {
        let q: Vec<String> = params.iter().map(|(k, v)| format!("{k}={v}")).collect();
        Ok(if q.is_empty() {
            format!("/{name}")
        } else {
            format!("/{name}?{}", q.join("&"))
        })
    }
    fn spark(&self, name: &str, props: &Value) -> Result<String, String> {
        let json = serde_json::to_string(props).map_err(|e| e.to_string())?;
        Ok(format!("<div data-spark=\"{name}\">{json}</div>"))
    }
    fn sparks_scripts(&self) -> String {
        "<script src=\"/sparks.js\"></script>".to_owned()
    }
    fn alloy_page(&self, id: &str) -> Result<String, String> {
        Ok(format!(
            "<script data-page=\"{id}\" type=\"application/json\">{{\"component\":\"welcome\"}}</script><div id=\"{id}\"></div>"
        ))
    }
    fn alloy_head(&self) -> String {
        "<meta name=\"alloy-head\">".to_owned()
    }
    fn vite(&self, entries: &[&str]) -> Result<String, String> {
        let entries = if entries.is_empty() {
            &["default.js"][..]
        } else {
            entries
        };
        Ok(entries
            .iter()
            .map(|e| format!("<script type=\"module\" src=\"/build/{e}\"></script>"))
            .collect())
    }
}

fn host() -> TestHost {
    TestHost {
        title_errors: vec!["Title is required".to_owned(), "second".to_owned()],
    }
}

fn check<T: Template>(case: &str, t: &T) {
    let expected = std::fs::read_to_string(format!(
        "{}/../smeltery-mold/tests/corpus/{case}/expected.html",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap();
    let h = host();
    let runtime = t
        .render_runtime(&h)
        .unwrap_or_else(|e| panic!("{case} runtime: {e}"));
    let compiled = t
        .render_compiled(&h)
        .unwrap_or_else(|e| panic!("{case} compiled: {e}"));
    assert_eq!(compiled, runtime, "{case}: compiled != runtime");
    assert_eq!(runtime, expected, "{case}: runtime != expected.html");
    assert_eq!(T::NAME, "page");
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/basics/views"
)]
struct Basics {
    title: String,
    html: &'static str,
    unicode: String,
    count: i32,
    flag: bool,
    ratio: f32,
    big_f: f64,
    small_f: f64,
    whole_f: f64,
    huge: u64,
    name: String,
    missing_opt: Option<String>,
    some_opt: Option<String>,
    empty: String,
    tags: Vec<String>,
    scores: BTreeMap<String, i64>,
}

#[test]
fn basics() {
    check(
        "basics",
        &Basics {
            title: "<Hello & 'World'>".into(),
            html: "<em>raw</em>",
            unicode: "héllo wörld ✓".into(),
            count: 5,
            flag: false,
            ratio: 0.1,
            big_f: 1e21,
            small_f: 0.000001,
            whole_f: 3.0,
            huge: u64::MAX,
            name: "Ann".into(),
            missing_opt: None,
            some_opt: Some("yes".into()),
            empty: String::new(),
            tags: vec!["x".into(), "y".into()],
            scores: BTreeMap::from([("math".to_owned(), 9)]),
        },
    );
}

#[derive(serde::Serialize)]
struct Post {
    title: String,
    tags: Vec<String>,
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/loops/views"
)]
struct Loops {
    posts: Vec<Post>,
    nothing: Vec<u8>,
    settings: BTreeMap<String, String>,
    names: Vec<&'static str>,
    maybe_list: Option<Vec<i32>>,
}

#[test]
fn loops() {
    check(
        "loops",
        &Loops {
            posts: vec![
                Post {
                    title: "First".into(),
                    tags: vec!["a".into(), "b".into()],
                },
                Post {
                    title: "Second".into(),
                    tags: vec![],
                },
            ],
            nothing: vec![],
            settings: BTreeMap::from([("color".into(), "red".into()), ("size".into(), "L".into())]),
            names: vec!["ann", "bob"],
            maybe_list: None,
        },
    );
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/layouts/views"
)]
struct Layouts<'a> {
    page_title: &'a str,
    user: String,
    site: std::borrow::Cow<'a, str>,
}

#[test]
fn layouts() {
    check(
        "layouts",
        &Layouts {
            page_title: "About & us",
            user: "ann".into(),
            site: "Smeltery".into(),
        },
    );
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/components/views"
)]
struct Components<T: serde::Serialize>
where
    T: Clone,
{
    items: Vec<T>,
    message: String,
    email: Box<str>,
}

#[test]
fn components() {
    check(
        "components",
        &Components {
            items: vec![1, 2, 3],
            message: "<script>".into(),
            email: "a@b.c".into(),
        },
    );
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/request/views"
)]
struct Request {
    post_id: u32,
    start: i64,
}

#[test]
fn request() {
    check(
        "request",
        &Request {
            post_id: 42,
            start: 5,
        },
    );
}

#[derive(Mold)]
#[mold("errors", crate = "smeltery_mold", dir = "tests/views")]
struct Errors {
    a: i64,
    b: i64,
    items: Vec<i64>,
}

#[test]
fn runtime_errors_match_in_both_modes() {
    let t = Errors {
        a: 1,
        b: 0,
        items: vec![],
    };
    let runtime = t.render_runtime(&smeltery_mold::NoHost).unwrap_err();
    let compiled = t.render_compiled(&smeltery_mold::NoHost).unwrap_err();
    assert_eq!(runtime.to_string(), compiled.to_string());
    assert_eq!(runtime.excerpt, compiled.excerpt);
    assert_eq!(
        compiled.to_string(),
        "tests/views/errors.mold.html:2:6: division by zero"
    );
}

#[test]
fn render_picks_the_build_mode() {
    let t = Request {
        post_id: 1,
        start: 2,
    };
    let h = host();
    assert_eq!(t.render(&h).unwrap(), t.render_compiled(&h).unwrap());
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/alloy/views"
)]
struct Alloy {
    title: String,
}

#[test]
fn alloy() {
    check(
        "alloy",
        &Alloy {
            title: "Forge <Alloy>".into(),
        },
    );
}

#[derive(Mold)]
#[mold("alloy_off", crate = "smeltery_mold", dir = "tests/views")]
struct AlloyOff {}

#[derive(Mold)]
#[mold("vite_off", crate = "smeltery_mold", dir = "tests/views")]
struct ViteOff {}

/// Without an Alloy host, `@alloy` and `@vite` fail the same way in both modes, at the directive; `@alloyHead`
/// renders nothing.
#[test]
fn alloy_without_a_host_fails_alike_in_both_modes() {
    let off = "Alloy is not enabled: call `.alloy(…)` in bootstrap/app.rs";
    for (runtime, compiled, at) in [
        (
            AlloyOff {}.render_runtime(&smeltery_mold::NoHost),
            AlloyOff {}.render_compiled(&smeltery_mold::NoHost),
            "tests/views/alloy_off.mold.html:3:3",
        ),
        (
            ViteOff {}.render_runtime(&smeltery_mold::NoHost),
            ViteOff {}.render_compiled(&smeltery_mold::NoHost),
            "tests/views/vite_off.mold.html:2:1",
        ),
    ] {
        let (runtime, compiled) = (runtime.unwrap_err(), compiled.unwrap_err());
        assert_eq!(runtime.to_string(), compiled.to_string());
        assert_eq!(runtime.excerpt, compiled.excerpt);
        assert_eq!(compiled.to_string(), format!("{at}: {off}"));
    }
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/adjacency/views"
)]
struct Adjacency {
    show: bool,
    name: String,
}

/// An `@` right after a word character never starts a directive (D-284): e-mail addresses with directive names and
/// `x@endif` stay text in both modes.
#[test]
fn adjacency() {
    check(
        "adjacency",
        &Adjacency {
            show: true,
            name: "Ann".into(),
        },
    );
}

#[derive(serde::Serialize)]
struct JsPost {
    title: String,
    views: u32,
}

#[derive(Mold)]
#[mold(
    "page",
    crate = "smeltery_mold",
    dir = "../smeltery-mold/tests/corpus/js/views"
)]
struct Js {
    name: String,
    id: u64,
    post: JsPost,
    tags: Vec<&'static str>,
    nothing: Option<String>,
    count: i32,
    ratio: f32,
    flag: bool,
    line: String,
    evil_url: String,
    hidden_url: String,
    data_url: String,
    good_url: String,
    rel_url: String,
    mail_url: String,
    colon_path: String,
}

/// The `json` and `url` filters produce the same bytes in both modes (S3-01, S3-09).
#[test]
fn js() {
    check(
        "js",
        &Js {
            name: "'+alert(1)+'\\</script><!--&\"".into(),
            id: 7,
            post: JsPost {
                title: "<b>x</b>".into(),
                views: 3,
            },
            tags: vec!["a", "b"],
            nothing: None,
            count: 5,
            ratio: 0.1,
            flag: true,
            line: "a\u{2028}b\u{2029}c".into(),
            evil_url: "JavaScript:alert(1)".into(),
            hidden_url: " \tjava\nscript:alert(2)".into(),
            data_url: "data:text/html,<script>alert(3)</script>".into(),
            good_url: "https://example.test/?a=1&b=2".into(),
            rel_url: "/posts/1".into(),
            mail_url: "mailto:me@example.test".into(),
            colon_path: "posts/a:b".into(),
        },
    );
}

#[derive(Mold)]
#[mold("safe_field", crate = "smeltery_mold", dir = "tests/views")]
struct SafeField {
    html: smeltery_mold::rt::Safe,
    text: String,
}

/// Slot HTML (`rt::Safe`) is written raw by both modes, also when it reaches a template as a field; plain strings
/// are escaped by both (S3-07: the interpreter used to escape it while compiled code did not).
#[test]
fn safe_values_render_alike_in_both_modes() {
    let t = SafeField {
        html: smeltery_mold::rt::Safe("<b>x</b>".into()),
        text: "<b>x</b>".into(),
    };
    let h = host();
    let runtime = t.render_runtime(&h).unwrap();
    assert_eq!(runtime, t.render_compiled(&h).unwrap());
    assert_eq!(
        runtime,
        "[<b>x</b>] [&lt;b&gt;x&lt;/b&gt;] [\"\\u003cb\\u003ex\\u003c/b\\u003e\"]\n"
    );
}
