//! The shared value semantics of Mold: display, escaping, truthiness, comparison, arithmetic and filters.
//!
//! The runtime interpreter applies these to [`Value`]; code generated by `#[derive(Mold)]` applies the same
//! functions to Rust values through the traits here. Both modes produce byte-identical output because both go
//! through this module.

use crate::Value;
use crate::ast::BinOp;
use crate::value::f32_to_f64;
use serde::Serialize;
use std::borrow::Cow;
use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;
use std::hash::BuildHasher;
use std::rc::Rc;
use std::sync::Arc;

/// HTML-escapes `s` (`& < > " '`) onto `out`.
pub fn escape_into(out: &mut String, s: &str) {
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
}

/// HTML-escapes `s`.
pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    escape_into(&mut out, s);
    out
}

/// Already-safe HTML, written without escaping: what a component slot renders to.
///
/// Internal to Mold (generated code builds slots with it). It renders raw in both modes: [`crate::to_value`] turns
/// it into [`Value::Safe`] for the interpreter, the same as the slot values the interpreter builds itself.
#[doc(hidden)]
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Safe(pub String);

/// The newtype-struct name `Safe` serializes under, so [`crate::to_value`] can tell it from a plain string.
pub(crate) const SAFE_NAME: &str = "__mold_safe";

impl Serialize for Safe {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        // Any other serializer (JSON included) sees the plain string.
        s.serialize_newtype_struct(SAFE_NAME, &self.0)
    }
}

/// The template `null` literal: displays as nothing, is falsy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize)]
pub struct Null;

/// The `loop` variable inside `@for`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[non_exhaustive]
pub struct Loop {
    /// 1-based position.
    pub index: usize,
    /// 0-based position.
    pub index0: usize,
    /// The first iteration.
    pub first: bool,
    /// The last iteration.
    pub last: bool,
    /// The number of items.
    pub count: usize,
}

impl Loop {
    /// The loop state for item `index0` of `count`.
    pub fn new(index0: usize, count: usize) -> Self {
        Self {
            index: index0 + 1,
            index0,
            first: index0 == 0,
            last: index0 + 1 == count,
            count,
        }
    }

    /// The same state as a map [`Value`], for the interpreter.
    pub fn to_value(&self) -> Value {
        let int = |n: usize| Value::Int(i64::try_from(n).unwrap_or(i64::MAX));
        Value::Map(vec![
            ("index".into(), int(self.index)),
            ("index0".into(), int(self.index0)),
            ("first".into(), Value::Bool(self.first)),
            ("last".into(), Value::Bool(self.last)),
            ("count".into(), int(self.count)),
        ])
    }
}

/// A scalar view of a value, used for comparisons, arithmetic and `default`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum Scalar<'a> {
    /// Nothing (`None`, `null`).
    Null,
    /// A boolean.
    Bool(bool),
    /// An integer that fits in `i64`.
    Int(i64),
    /// An integer above `i64::MAX`.
    UInt(u64),
    /// A float.
    Float(f64),
    /// A string.
    Str(Cow<'a, str>),
}

impl Scalar<'_> {
    /// Detaches the scalar from what it borrows.
    pub fn into_owned(self) -> Scalar<'static> {
        match self {
            Scalar::Null => Scalar::Null,
            Scalar::Bool(b) => Scalar::Bool(b),
            Scalar::Int(i) => Scalar::Int(i),
            Scalar::UInt(u) => Scalar::UInt(u),
            Scalar::Float(f) => Scalar::Float(f),
            Scalar::Str(s) => Scalar::Str(Cow::Owned(s.into_owned())),
        }
    }

    fn kind(&self) -> &'static str {
        match self {
            Scalar::Null => "null",
            Scalar::Bool(_) => "a boolean",
            Scalar::Int(_) | Scalar::UInt(_) => "an integer",
            Scalar::Float(_) => "a float",
            Scalar::Str(_) => "a string",
        }
    }

    fn as_i128(&self) -> Option<i128> {
        match self {
            Scalar::Int(i) => Some((*i).into()),
            Scalar::UInt(u) => Some((*u).into()),
            _ => None,
        }
    }

    fn as_f64(&self) -> Option<f64> {
        match self {
            Scalar::Int(i) => Some(*i as f64),
            Scalar::UInt(u) => Some(*u as f64),
            Scalar::Float(f) => Some(*f),
            _ => None,
        }
    }
}

impl From<Scalar<'_>> for Value {
    fn from(s: Scalar<'_>) -> Self {
        match s {
            Scalar::Null => Value::Null,
            Scalar::Bool(b) => Value::Bool(b),
            Scalar::Int(i) => Value::Int(i),
            Scalar::UInt(u) => Value::UInt(u),
            Scalar::Float(f) => Value::Float(f),
            Scalar::Str(s) => Value::Str(s.into_owned()),
        }
    }
}

fn int_scalar(i: i128) -> Option<Scalar<'static>> {
    if let Ok(v) = i64::try_from(i) {
        Some(Scalar::Int(v))
    } else {
        u64::try_from(i).ok().map(Scalar::UInt)
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Render

/// Writes a value's display form, HTML-escaped when `escape` is true. [`Safe`] is never escaped.
pub trait Render {
    /// Appends the display form to `out`.
    fn render(&self, out: &mut String, escape: bool);
}

/// The unescaped display form of `value` (what filters work on).
pub fn display<R: Render + ?Sized>(value: &R) -> String {
    let mut out = String::new();
    value.render(&mut out, false);
    out
}

fn push_str(out: &mut String, s: &str, escape: bool) {
    if escape {
        escape_into(out, s);
    } else {
        out.push_str(s);
    }
}

macro_rules! render_display {
    ($($t:ty),*) => {$(
        impl Render for $t {
            fn render(&self, out: &mut String, _escape: bool) {
                let _ = write!(out, "{}", self);
            }
        }
    )*};
}
render_display!(
    i8, i16, i32, i64, i128, isize, u8, u16, u32, u64, u128, usize, f32, f64, bool
);

impl Render for char {
    fn render(&self, out: &mut String, escape: bool) {
        push_str(out, self.encode_utf8(&mut [0; 4]), escape);
    }
}
impl Render for str {
    fn render(&self, out: &mut String, escape: bool) {
        push_str(out, self, escape);
    }
}
impl Render for String {
    fn render(&self, out: &mut String, escape: bool) {
        push_str(out, self, escape);
    }
}
impl Render for Safe {
    fn render(&self, out: &mut String, _escape: bool) {
        out.push_str(&self.0);
    }
}
impl Render for Null {
    fn render(&self, _out: &mut String, _escape: bool) {}
}
impl Render for Scalar<'_> {
    fn render(&self, out: &mut String, escape: bool) {
        match self {
            Scalar::Null => {}
            Scalar::Bool(b) => b.render(out, escape),
            Scalar::Int(i) => i.render(out, escape),
            Scalar::UInt(u) => u.render(out, escape),
            Scalar::Float(f) => f.render(out, escape),
            Scalar::Str(s) => push_str(out, s, escape),
        }
    }
}
impl<T: Render> Render for Option<T> {
    fn render(&self, out: &mut String, escape: bool) {
        if let Some(v) = self {
            v.render(out, escape);
        }
    }
}
impl<T: Render + ?Sized> Render for &T {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}
impl<T: Render + ?Sized> Render for &mut T {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}
impl<T: Render + ?Sized> Render for Box<T> {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}
impl<T: Render + ?Sized> Render for Rc<T> {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}
impl<T: Render + ?Sized> Render for Arc<T> {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}
impl<B: Render + ToOwned + ?Sized> Render for Cow<'_, B> {
    fn render(&self, out: &mut String, escape: bool) {
        (**self).render(out, escape);
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Truthy

/// Truthiness: `false`, `0`, `0.0`, `""`, empty lists and maps, and `None` are falsy.
pub trait Truthy {
    /// Whether the value counts as true in `@if`, `!`, `&&` and `||`.
    fn truthy(&self) -> bool;
}

macro_rules! truthy_num {
    ($($t:ty),*) => {$(
        impl Truthy for $t {
            fn truthy(&self) -> bool { *self != (0 as $t) }
        }
    )*};
}
truthy_num!(
    i8, i16, i32, i64, i128, isize, u8, u16, u32, u64, u128, usize, f32, f64
);

impl Truthy for bool {
    fn truthy(&self) -> bool {
        *self
    }
}
impl Truthy for char {
    fn truthy(&self) -> bool {
        true
    }
}
impl Truthy for str {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl Truthy for String {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl Truthy for Safe {
    fn truthy(&self) -> bool {
        !self.0.is_empty()
    }
}
impl Truthy for Null {
    fn truthy(&self) -> bool {
        false
    }
}
impl Truthy for Scalar<'_> {
    fn truthy(&self) -> bool {
        match self {
            Scalar::Null => false,
            Scalar::Bool(b) => *b,
            Scalar::Int(i) => *i != 0,
            Scalar::UInt(u) => *u != 0,
            Scalar::Float(f) => *f != 0.0,
            Scalar::Str(s) => !s.is_empty(),
        }
    }
}
impl<T> Truthy for [T] {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl<T> Truthy for Vec<T> {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl<K, V, S> Truthy for HashMap<K, V, S> {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl<K, V> Truthy for BTreeMap<K, V> {
    fn truthy(&self) -> bool {
        !self.is_empty()
    }
}
impl<T: Truthy> Truthy for Option<T> {
    fn truthy(&self) -> bool {
        self.as_ref().is_some_and(Truthy::truthy)
    }
}
impl<T: Truthy + ?Sized> Truthy for &T {
    fn truthy(&self) -> bool {
        (**self).truthy()
    }
}
impl<T: Truthy + ?Sized> Truthy for Box<T> {
    fn truthy(&self) -> bool {
        (**self).truthy()
    }
}
impl<T: Truthy + ?Sized> Truthy for Rc<T> {
    fn truthy(&self) -> bool {
        (**self).truthy()
    }
}
impl<T: Truthy + ?Sized> Truthy for Arc<T> {
    fn truthy(&self) -> bool {
        (**self).truthy()
    }
}
impl<B: Truthy + ToOwned + ?Sized> Truthy for Cow<'_, B> {
    fn truthy(&self) -> bool {
        (**self).truthy()
    }
}

/// Truthiness for generated code, also for types without a [`Truthy`] impl.
///
/// Generated code calls `(&&Probe(&value)).mold_truthy()`; method resolution picks the first that applies:
/// [`ViaTruthy`] (the type implements `Truthy`), [`ViaOption`] (an `Option` of any type: `is_some`), [`ViaAny`]
/// (any other value, such as a struct: true). This matches the interpreter, where a struct is a non-empty map.
pub struct Probe<'a, T: ?Sized>(pub &'a T);

impl<T: ?Sized> Clone for Probe<'_, T> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T: ?Sized> Copy for Probe<'_, T> {}

/// See [`Probe`].
pub trait ViaTruthy {
    /// Truthiness.
    fn mold_truthy(self) -> bool;
}
impl<T: Truthy + ?Sized> ViaTruthy for &&Probe<'_, T> {
    fn mold_truthy(self) -> bool {
        self.0.truthy()
    }
}
/// See [`Probe`].
pub trait ViaOption {
    /// Truthiness.
    fn mold_truthy(self) -> bool;
}
impl<T> ViaOption for &Probe<'_, Option<T>> {
    fn mold_truthy(self) -> bool {
        self.0.is_some()
    }
}
/// See [`Probe`].
pub trait ViaAny {
    /// Truthiness.
    fn mold_truthy(self) -> bool;
}
impl<T: ?Sized> ViaAny for Probe<'_, T> {
    fn mold_truthy(self) -> bool {
        true
    }
}

// ---------------------------------------------------------------------------------------------------------------
// ToScalar

/// The scalar view used by comparisons, arithmetic and `default`.
pub trait ToScalar {
    /// This value as a [`Scalar`].
    fn to_scalar(&self) -> Scalar<'_>;
}

macro_rules! scalar_int {
    ($($t:ty),*) => {$(
        impl ToScalar for $t {
            fn to_scalar(&self) -> Scalar<'_> { int_scalar(*self as i128).unwrap_or(Scalar::Null) }
        }
    )*};
}
scalar_int!(i8, i16, i32, i64, isize, u8, u16, u32, u64, usize);

impl ToScalar for f32 {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Float(f32_to_f64(*self))
    }
}
impl ToScalar for f64 {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Float(*self)
    }
}
impl ToScalar for bool {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Bool(*self)
    }
}
impl ToScalar for char {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Str(Cow::Owned(self.to_string()))
    }
}
impl ToScalar for str {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Str(Cow::Borrowed(self))
    }
}
impl ToScalar for String {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Str(Cow::Borrowed(self))
    }
}
impl ToScalar for Safe {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Str(Cow::Borrowed(&self.0))
    }
}
impl ToScalar for Null {
    fn to_scalar(&self) -> Scalar<'_> {
        Scalar::Null
    }
}
impl ToScalar for Scalar<'_> {
    fn to_scalar(&self) -> Scalar<'_> {
        match self {
            Scalar::Str(s) => Scalar::Str(Cow::Borrowed(s)),
            other => other.clone(),
        }
    }
}
impl<T: ToScalar> ToScalar for Option<T> {
    fn to_scalar(&self) -> Scalar<'_> {
        self.as_ref().map_or(Scalar::Null, ToScalar::to_scalar)
    }
}
impl<T: ToScalar + ?Sized> ToScalar for &T {
    fn to_scalar(&self) -> Scalar<'_> {
        (**self).to_scalar()
    }
}
impl<T: ToScalar + ?Sized> ToScalar for Box<T> {
    fn to_scalar(&self) -> Scalar<'_> {
        (**self).to_scalar()
    }
}
impl<T: ToScalar + ?Sized> ToScalar for Rc<T> {
    fn to_scalar(&self) -> Scalar<'_> {
        (**self).to_scalar()
    }
}
impl<T: ToScalar + ?Sized> ToScalar for Arc<T> {
    fn to_scalar(&self) -> Scalar<'_> {
        (**self).to_scalar()
    }
}
impl<B: ToScalar + ToOwned + ?Sized> ToScalar for Cow<'_, B> {
    fn to_scalar(&self) -> Scalar<'_> {
        (**self).to_scalar()
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Len

/// The `len` filter: characters of a string, items of a list or map, 0 for `None`.
pub trait Len {
    /// The length, or why this value has none.
    fn mold_len(&self) -> Result<usize, String>;
}
impl Len for str {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.chars().count())
    }
}
impl Len for String {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.chars().count())
    }
}
impl Len for Safe {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.0.chars().count())
    }
}
impl Len for Null {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(0)
    }
}
impl Len for Scalar<'_> {
    fn mold_len(&self) -> Result<usize, String> {
        match self {
            Scalar::Null => Ok(0),
            Scalar::Str(s) => Ok(s.chars().count()),
            other => Err(format!(
                "`len` needs a string, list or map, not {}",
                other.kind()
            )),
        }
    }
}
impl<T> Len for [T] {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.len())
    }
}
impl<T> Len for Vec<T> {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.len())
    }
}
impl<K, V, S> Len for HashMap<K, V, S> {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.len())
    }
}
impl<K, V> Len for BTreeMap<K, V> {
    fn mold_len(&self) -> Result<usize, String> {
        Ok(self.len())
    }
}
impl<T: Len> Len for Option<T> {
    fn mold_len(&self) -> Result<usize, String> {
        self.as_ref().map_or(Ok(0), Len::mold_len)
    }
}
impl<T: Len + ?Sized> Len for &T {
    fn mold_len(&self) -> Result<usize, String> {
        (**self).mold_len()
    }
}
impl<T: Len + ?Sized> Len for Box<T> {
    fn mold_len(&self) -> Result<usize, String> {
        (**self).mold_len()
    }
}
impl<T: Len + ?Sized> Len for Rc<T> {
    fn mold_len(&self) -> Result<usize, String> {
        (**self).mold_len()
    }
}
impl<T: Len + ?Sized> Len for Arc<T> {
    fn mold_len(&self) -> Result<usize, String> {
        (**self).mold_len()
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Iterate / Index

/// What `@for` loops over: lists (keys are 0-based indexes), maps (keys are the map keys) and `Option`s of them
/// (`None` iterates nothing).
pub trait Iterate {
    /// The key type (`usize` for lists).
    type Key<'a>
    where
        Self: 'a;
    /// The item type.
    type Item: ?Sized;
    /// The number of items.
    fn mold_count(&self) -> usize;
    /// Keys and items, in iteration order.
    fn mold_iter(&self) -> impl Iterator<Item = (Self::Key<'_>, &Self::Item)>;
}

impl<T> Iterate for [T] {
    type Key<'a>
        = usize
    where
        T: 'a;
    type Item = T;
    fn mold_count(&self) -> usize {
        self.len()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (usize, &T)> {
        self.iter().enumerate()
    }
}
impl<T> Iterate for Vec<T> {
    type Key<'a>
        = usize
    where
        T: 'a;
    type Item = T;
    fn mold_count(&self) -> usize {
        self.len()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (usize, &T)> {
        self.iter().enumerate()
    }
}
impl<K, V, S: BuildHasher> Iterate for HashMap<K, V, S> {
    type Key<'a>
        = &'a K
    where
        Self: 'a;
    type Item = V;
    fn mold_count(&self) -> usize {
        self.len()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (&K, &V)> {
        self.iter()
    }
}
impl<K, V> Iterate for BTreeMap<K, V> {
    type Key<'a>
        = &'a K
    where
        Self: 'a;
    type Item = V;
    fn mold_count(&self) -> usize {
        self.len()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (&K, &V)> {
        self.iter()
    }
}
impl<T: Iterate> Iterate for Option<T> {
    type Key<'a>
        = T::Key<'a>
    where
        Self: 'a;
    type Item = T::Item;
    fn mold_count(&self) -> usize {
        self.as_ref().map_or(0, Iterate::mold_count)
    }
    fn mold_iter(&self) -> impl Iterator<Item = (T::Key<'_>, &T::Item)> {
        self.as_ref().into_iter().flat_map(Iterate::mold_iter)
    }
}
impl<T: Iterate + ?Sized> Iterate for &T {
    type Key<'a>
        = T::Key<'a>
    where
        Self: 'a;
    type Item = T::Item;
    fn mold_count(&self) -> usize {
        (**self).mold_count()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (T::Key<'_>, &T::Item)> {
        (**self).mold_iter()
    }
}
impl<T: Iterate + ?Sized> Iterate for Box<T> {
    type Key<'a>
        = T::Key<'a>
    where
        Self: 'a;
    type Item = T::Item;
    fn mold_count(&self) -> usize {
        (**self).mold_count()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (T::Key<'_>, &T::Item)> {
        (**self).mold_iter()
    }
}
impl<T: Iterate + ?Sized> Iterate for Rc<T> {
    type Key<'a>
        = T::Key<'a>
    where
        Self: 'a;
    type Item = T::Item;
    fn mold_count(&self) -> usize {
        (**self).mold_count()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (T::Key<'_>, &T::Item)> {
        (**self).mold_iter()
    }
}
impl<T: Iterate + ?Sized> Iterate for Arc<T> {
    type Key<'a>
        = T::Key<'a>
    where
        Self: 'a;
    type Item = T::Item;
    fn mold_count(&self) -> usize {
        (**self).mold_count()
    }
    fn mold_iter(&self) -> impl Iterator<Item = (T::Key<'_>, &T::Item)> {
        (**self).mold_iter()
    }
}

/// `a[i]`: lists by integer index, maps by string key.
pub trait Indexable {
    /// The item type.
    type Output: ?Sized;
    /// The item at `key`, or why there is none.
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&Self::Output, String>;
}

fn list_index<'a, T>(items: &'a [T], key: &Scalar<'_>) -> Result<&'a T, String> {
    let i = key
        .as_i128()
        .ok_or_else(|| format!("a list index must be an integer, not {}", key.kind()))?;
    usize::try_from(i)
        .ok()
        .and_then(|i| items.get(i))
        .ok_or_else(|| {
            format!(
                "index {i} is out of range for a list of {} items",
                items.len()
            )
        })
}

fn map_key(key: &Scalar<'_>) -> String {
    display(key)
}

impl<T> Indexable for [T] {
    type Output = T;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T, String> {
        list_index(self, key)
    }
}
impl<T> Indexable for Vec<T> {
    type Output = T;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T, String> {
        list_index(self, key)
    }
}
impl<K: std::borrow::Borrow<str> + std::hash::Hash + Eq, V, S: BuildHasher> Indexable
    for HashMap<K, V, S>
{
    type Output = V;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&V, String> {
        let k = map_key(key);
        self.get(k.as_str())
            .ok_or_else(|| format!("no key `{k}` in the map"))
    }
}
impl<K: std::borrow::Borrow<str> + Ord, V> Indexable for BTreeMap<K, V> {
    type Output = V;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&V, String> {
        let k = map_key(key);
        self.get(k.as_str())
            .ok_or_else(|| format!("no key `{k}` in the map"))
    }
}
impl<T: Indexable + ?Sized> Indexable for &T {
    type Output = T::Output;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T::Output, String> {
        (**self).mold_index(key)
    }
}
impl<T: Indexable + ?Sized> Indexable for Box<T> {
    type Output = T::Output;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T::Output, String> {
        (**self).mold_index(key)
    }
}
impl<T: Indexable + ?Sized> Indexable for Rc<T> {
    type Output = T::Output;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T::Output, String> {
        (**self).mold_index(key)
    }
}
impl<T: Indexable + ?Sized> Indexable for Arc<T> {
    type Output = T::Output;
    fn mold_index(&self, key: &Scalar<'_>) -> Result<&T::Output, String> {
        (**self).mold_index(key)
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Operators

/// `==` / `!=`: numbers compare numerically (an integer equals a float of the same value), strings by bytes,
/// `null` only equals `null`, values of different kinds are not equal.
pub fn equals(a: &Scalar<'_>, b: &Scalar<'_>) -> bool {
    match (a, b) {
        (Scalar::Null, Scalar::Null) => true,
        (Scalar::Bool(x), Scalar::Bool(y)) => x == y,
        (Scalar::Str(x), Scalar::Str(y)) => x == y,
        _ => match (a.as_i128(), b.as_i128()) {
            (Some(x), Some(y)) => x == y,
            _ => match (a.as_f64(), b.as_f64()) {
                (Some(x), Some(y)) => x == y,
                _ => false,
            },
        },
    }
}

/// A comparison operator (`== != < <= > >=`) applied to two scalars.
pub fn compare(op: BinOp, a: &Scalar<'_>, b: &Scalar<'_>) -> Result<bool, String> {
    use std::cmp::Ordering;
    let ord = match op {
        BinOp::Eq => return Ok(equals(a, b)),
        BinOp::Ne => return Ok(!equals(a, b)),
        _ => match (a, b) {
            (Scalar::Str(x), Scalar::Str(y)) => Some(x.as_bytes().cmp(y.as_bytes())),
            (Scalar::Bool(x), Scalar::Bool(y)) => Some(x.cmp(y)),
            _ => match (a.as_i128(), b.as_i128()) {
                (Some(x), Some(y)) => Some(x.cmp(&y)),
                _ => match (a.as_f64(), b.as_f64()) {
                    (Some(x), Some(y)) => x.partial_cmp(&y),
                    _ => return Err(format!("cannot compare {} with {}", a.kind(), b.kind())),
                },
            },
        },
    };
    Ok(match (op, ord) {
        (_, None) => false,
        (BinOp::Lt, Some(o)) => o == Ordering::Less,
        (BinOp::Le, Some(o)) => o != Ordering::Greater,
        (BinOp::Gt, Some(o)) => o == Ordering::Greater,
        (BinOp::Ge, Some(o)) => o != Ordering::Less,
        _ => false,
    })
}

/// An arithmetic operator (`+ - * / %`). Integers stay integers (overflow and division by zero are errors), any
/// float makes a float, `+` on two strings concatenates.
pub fn arith(op: BinOp, a: &Scalar<'_>, b: &Scalar<'_>) -> Result<Scalar<'static>, String> {
    if let (BinOp::Add, Scalar::Str(x), Scalar::Str(y)) = (op, a, b) {
        return Ok(Scalar::Str(Cow::Owned(format!("{x}{y}"))));
    }
    let sym = op.symbol();
    if let (Some(x), Some(y)) = (a.as_i128(), b.as_i128()) {
        let r = match op {
            BinOp::Add => x.checked_add(y),
            BinOp::Sub => x.checked_sub(y),
            BinOp::Mul => x.checked_mul(y),
            BinOp::Div | BinOp::Rem if y == 0 => return Err("division by zero".to_owned()),
            BinOp::Div => x.checked_div(y),
            BinOp::Rem => x.checked_rem(y),
            _ => None,
        };
        return r
            .and_then(int_scalar)
            .ok_or_else(|| format!("integer overflow in `{x} {sym} {y}`"));
    }
    match (a.as_f64(), b.as_f64()) {
        (Some(x), Some(y)) => Ok(Scalar::Float(match op {
            BinOp::Add => x + y,
            BinOp::Sub => x - y,
            BinOp::Mul => x * y,
            BinOp::Div => x / y,
            _ => x % y,
        })),
        _ => Err(format!(
            "cannot apply `{sym}` to {} and {}",
            a.kind(),
            b.kind()
        )),
    }
}

/// Unary minus.
pub fn neg(a: &Scalar<'_>) -> Result<Scalar<'static>, String> {
    match a {
        Scalar::Float(f) => Ok(Scalar::Float(-f)),
        _ => match a.as_i128() {
            Some(i) => int_scalar(-i).ok_or_else(|| format!("integer overflow in `-{i}`")),
            None => Err(format!("cannot negate {}", a.kind())),
        },
    }
}

// ---------------------------------------------------------------------------------------------------------------
// Filters and functions

/// The `upper` filter.
pub fn upper(s: &str) -> String {
    s.to_uppercase()
}
/// The `lower` filter.
pub fn lower(s: &str) -> String {
    s.to_lowercase()
}
/// The `trim` filter.
pub fn trim(s: &str) -> String {
    s.trim().to_owned()
}
/// The `title` filter: the first letter of each word upper case, the rest lower case.
pub fn title(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut start = true;
    for c in s.chars() {
        if c.is_whitespace() {
            start = true;
            out.push(c);
        } else if start {
            out.extend(c.to_uppercase());
            start = false;
        } else {
            out.extend(c.to_lowercase());
        }
    }
    out
}
/// The `default(x)` filter: `x` when the value is null or an empty string.
pub fn default(value: Scalar<'_>, fallback: Scalar<'_>) -> Scalar<'static> {
    match &value {
        Scalar::Null => fallback.into_owned(),
        Scalar::Str(s) if s.is_empty() => fallback.into_owned(),
        _ => value.into_owned(),
    }
}
/// The `join(sep)` filter.
pub fn join<T>(items: &T, sep: &str) -> String
where
    T: Iterate + ?Sized,
    T::Item: Render,
{
    let mut out = String::new();
    for (i, (_, item)) in items.mold_iter().enumerate() {
        if i > 0 {
            out.push_str(sep);
        }
        item.render(&mut out, false);
    }
    out
}

/// The `json` filter: `value` as JSON, which is also a JavaScript literal, with `<`, `>`, `&`, `'`, U+2028 and
/// U+2029 written as `\uXXXX` escapes.
///
/// Those characters can only occur inside JSON strings, where the escapes mean the same thing, so the result is
/// still the same JSON. Without them the text cannot end a `<script>` element, open an HTML comment or entity, close
/// a single-quoted attribute, or break a line in older JavaScript parsers. Echoed with `{{ }}` the remaining `"`
/// become `&quot;`, which the browser decodes before an attribute's JavaScript runs (`x-data`, `@click`,
/// `wire:click`); inside `<script>` (no entity decoding) it is echoed raw with `{!! !!}`. Both modes serialize the
/// value with `serde_json`, so their output is identical.
pub fn json<T: Serialize + ?Sized>(value: &T) -> Result<String, String> {
    let text =
        serde_json::to_string(value).map_err(|e| format!("`json` cannot encode the value: {e}"))?;
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '<' => out.push_str("\\u003c"),
            '>' => out.push_str("\\u003e"),
            '&' => out.push_str("\\u0026"),
            '\'' => out.push_str("\\u0027"),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c => out.push(c),
        }
    }
    Ok(out)
}

/// The URL schemes the `url` filter keeps.
const URL_SCHEMES: &[&str] = &["http", "https", "mailto", "tel"];

/// The `url` filter: `s` unchanged when it is a relative URL or an absolute one with the scheme `http`, `https`,
/// `mailto` or `tel`; `#` otherwise (`javascript:`, `data:`, `vbscript:`, …).
///
/// The scheme is found the way browsers find it: leading and trailing spaces and control characters are ignored and
/// tabs and line breaks removed, so ` java\nscript:` counts as `javascript:`. An `&`, a BOM or another control
/// character before the first `/`, `?` or `#` also gives `#` (an entity such as `&#58;` would be decoded by the
/// browser when the value is echoed raw).
pub fn url(s: &str) -> String {
    // Before the path, query or fragment: an `&` (an HTML entity such as `&#58;`, decoded by the browser when the
    // value is echoed raw), a NUL, a BOM or another control character makes the scheme unknowable here: refused.
    let head = s.split(['/', '?', '#']).next().unwrap_or_default();
    if head.chars().any(|c| {
        c == '&' || c == '\u{feff}' || (c.is_control() && !matches!(c, '\t' | '\n' | '\r' | ' '))
    }) {
        return "#".to_owned();
    }
    let cleaned: String = s
        .trim_matches(|c: char| c <= ' ')
        .chars()
        .filter(|c| !matches!(c, '\t' | '\n' | '\r'))
        .collect();
    // A scheme is an ASCII letter followed by letters, digits, `+`, `-` or `.`, up to the first `:`; anything else
    // before the first `:` (or no `:` at all) makes the URL relative.
    let scheme = cleaned
        .split_once(':')
        .map(|(head, _)| head)
        .filter(|head| {
            let mut chars = head.chars();
            chars.next().is_some_and(|c| c.is_ascii_alphabetic())
                && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '+' | '-' | '.'))
        });
    match scheme {
        Some(scheme) if !URL_SCHEMES.iter().any(|ok| scheme.eq_ignore_ascii_case(ok)) => {
            "#".to_owned()
        }
        _ => s.to_owned(),
    }
}

/// What `@csrf` writes, or the error when the host has no token.
pub fn csrf_field(host: &dyn crate::Host) -> Result<String, String> {
    let token = csrf_token(host)?;
    let mut out = String::from("<input type=\"hidden\" name=\"_token\" value=\"");
    escape_into(&mut out, token);
    out.push_str("\">");
    Ok(out)
}

/// The `csrf_token()` function.
pub fn csrf_token(host: &dyn crate::Host) -> Result<&str, String> {
    host.csrf_token()
        .ok_or_else(|| "no CSRF token available (is the session middleware installed?)".to_owned())
}

/// What `@method("PUT")` writes.
pub fn method_field(method: &str) -> String {
    let mut out = String::from("<input type=\"hidden\" name=\"_method\" value=\"");
    escape_into(&mut out, method);
    out.push_str("\">");
    out
}

/// An error raised by generated code at a template position.
pub fn error_at(
    file: &str,
    source: &str,
    line: u32,
    col: u32,
    message: impl Into<String>,
) -> crate::Error {
    crate::Error::at(file, source, line, col, message)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &str) -> Scalar<'_> {
        Scalar::Str(Cow::Borrowed(v))
    }

    #[test]
    fn escaping() {
        assert_eq!(
            escape("<a href=\"x\">'&'</a>"),
            "&lt;a href=&quot;x&quot;&gt;&#39;&amp;&#39;&lt;/a&gt;"
        );
    }

    #[test]
    fn comparisons() {
        assert!(equals(&Scalar::Int(1), &Scalar::Float(1.0)));
        assert!(!equals(&Scalar::Int(1), &s("1")));
        assert!(equals(&Scalar::UInt(u64::MAX), &Scalar::UInt(u64::MAX)));
        assert!(compare(BinOp::Lt, &Scalar::Int(1), &Scalar::Float(1.5)).unwrap());
        assert!(compare(BinOp::Ge, &s("b"), &s("a")).unwrap());
        assert!(compare(BinOp::Lt, &s("a"), &Scalar::Int(1)).is_err());
        assert!(!compare(BinOp::Lt, &Scalar::Float(f64::NAN), &Scalar::Int(1)).unwrap());
    }

    #[test]
    fn arithmetic() {
        assert_eq!(
            arith(BinOp::Add, &Scalar::Int(2), &Scalar::Int(3)).unwrap(),
            Scalar::Int(5)
        );
        assert_eq!(
            arith(BinOp::Div, &Scalar::Int(7), &Scalar::Int(2)).unwrap(),
            Scalar::Int(3)
        );
        assert_eq!(
            arith(BinOp::Div, &Scalar::Int(7), &Scalar::Float(2.0)).unwrap(),
            Scalar::Float(3.5)
        );
        assert_eq!(
            arith(BinOp::Add, &s("a"), &s("b")).unwrap(),
            Scalar::Str("ab".into())
        );
        assert!(arith(BinOp::Div, &Scalar::Int(1), &Scalar::Int(0)).is_err());
        assert!(arith(BinOp::Mul, &Scalar::UInt(u64::MAX), &Scalar::Int(2)).is_err());
        assert_eq!(
            arith(BinOp::Add, &Scalar::Int(i64::MAX), &Scalar::Int(1)).unwrap(),
            Scalar::UInt(i64::MAX as u64 + 1)
        );
        assert!(arith(BinOp::Add, &s("a"), &Scalar::Int(1)).is_err());
        assert_eq!(neg(&Scalar::Int(3)).unwrap(), Scalar::Int(-3));
        assert!(neg(&s("x")).is_err());
    }

    #[test]
    #[allow(clippy::needless_borrow)] // The extra borrows are what select the impl.
    fn truthiness_and_probe() {
        use super::{ViaAny as _, ViaOption as _, ViaTruthy as _};
        struct User;
        assert!(!(&&Probe(&0)).mold_truthy());
        assert!(!(&&Probe(&Some(""))).mold_truthy());
        assert!((&&Probe(&Some(User))).mold_truthy());
        assert!(!(&&Probe(&None::<User>)).mold_truthy());
        assert!((&&Probe(&User)).mold_truthy());
        assert!(!(&&Probe(&Vec::<User>::new())).mold_truthy());
    }

    #[test]
    fn json_filter_escapes_html_and_line_separators() {
        let v = json("</script><!--&'\u{2028}\u{2029}\"\\").unwrap();
        let bs = '\\';
        let expected = format!(
            "\"{bs}u003c/script{bs}u003e{bs}u003c!--{bs}u0026{bs}u0027{bs}u2028{bs}u2029{bs}\"{bs}{bs}\""
        );
        assert_eq!(v, expected);
        // Still JSON meaning the same value.
        let back: String = serde_json::from_str(&v).unwrap();
        assert_eq!(back, "</script><!--&'\u{2028}\u{2029}\"\\");
        assert_eq!(json(&Some(1.5)).unwrap(), "1.5");
        assert_eq!(json(&None::<i32>).unwrap(), "null");
        assert_eq!(json(&vec!["a"]).unwrap(), r#"["a"]"#);
    }

    #[test]
    fn url_filter_keeps_only_harmless_schemes() {
        for ok in [
            "/a",
            "a/b:c",
            "?q=x:y",
            "#top",
            "//cdn.example.test/x",
            "https://example.test/?a=1&b=2",
            "HTTP://x",
            "mailto:me@example.test",
            "tel:+123",
            "",
        ] {
            assert_eq!(url(ok), ok, "{ok}");
        }
        for bad in [
            "javascript:alert(1)",
            "JavaScript:alert(1)",
            " \tjava\nscript:alert(1)",
            "\u{1}javascript:x",
            "data:text/html,x",
            "vbscript:x",
            "blob:https://x",
        ] {
            assert_eq!(url(bad), "#", "{bad:?}");
        }
    }

    /// Echoed raw (`{!! !!}`), the browser decodes entities before it reads the scheme: an `&` before the path, a
    /// BOM or a NUL there is refused (S3-09 re-check).
    #[test]
    fn url_filter_refuses_entities_and_invisible_prefixes_before_the_path() {
        for bad in [
            "javascript&#58;alert(1)",
            "&#106;avascript:alert(1)",
            "java&Tab;script:alert(1)",
            "javascript&colon;alert(1)",
            "\u{feff}javascript:alert(1)",
            "\u{0}javascript:alert(1)",
            "a&b",
        ] {
            assert_eq!(url(bad), "#", "{bad:?}");
        }
        for ok in [
            "/a?x=1&y=2",
            "/a&b",
            "https://x.test/?a=1&b=2",
            "?a&b",
            "#a&b",
        ] {
            assert_eq!(url(ok), ok, "{ok}");
        }
    }

    #[test]
    fn filters() {
        assert_eq!(title("hello wORLD"), "Hello World");
        assert_eq!(default(Scalar::Null, s("x")), s("x"));
        assert_eq!(default(Scalar::Int(0), s("x")), Scalar::Int(0));
        assert_eq!(join(&vec![1, 2, 3], ", "), "1, 2, 3");
        assert_eq!(display(&0.1f32), "0.1");
        assert_eq!(Some(3).to_scalar(), Scalar::Int(3));
        assert_eq!(Len::mold_len(&Some("héllo")).unwrap(), 5);
    }
}
